version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: card-scraper
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=${API_URL}
      - PYTHONDONTWRITEBYTECODE=1
      - MALLOC_ARENA_MAX=2
      - PYTHONPATH=/app
      - CONFIG_PATH=configs/prod_config.json
    volumes:
      - ./logs:/app/logs
      - /tmp:/tmp
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

    
    deploy:
      resources:
        limits:
          memory: 850M        
          cpus: '0.8'         
        reservations:
          memory: 400M        
          cpus: '0.2'         
    
    shm_size: 128mb
    
    cap_add:
      - SYS_ADMIN        
    security_opt:
      - seccomp:unconfined 
    

    

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

