version: '3.8'

services:
  app:
    build: .
    container_name: card-scraper
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped