name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_KEY }}
        script: |
          cd /home/ubuntu/CardsScraper || {
            echo "First time - cloning repository"
            git clone https://github.com/${{ github.repository }}.git CardsScraper
            cd CardsScraper
          }
          
          echo "Updating code..."
          git pull origin main
          
          echo "Activating virtual environment..."
          source venv/bin/activate
          
          echo "Installing dependencies..."
          pip install -r requirements.txt
